name: Test PR content into staging or production
on:
  pull_request:
    branches:
      - staging, production
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: cicd-sample-app
  REGION: us-central1
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # build container image from source branch  
    - name: Build Container
      run: |-
        docker build -t temp:latest .
      
    # run container with unit test entry point - TODO
    
    # run container with integration test entry point - TODO
